hello: ENC[AES256_GCM,data:ep4yo7OoKsVfeGoVQ5S1T+6kLuTYTqVNPpNLuvnkajgV9O0gl+hiyem/aQdd6A==,iv:OCfTV6WqBbnT+VeD7porDOExm3QImIaRlfpl8JN7yyM=,tag:SjFV5ZKzqDUsKDg4h6/k5A==,type:str]
example_key: ENC[AES256_GCM,data:xF8T1A7CBwKardl8Og==,iv:E0z2NBeOtd0PG3oo+ioh3zQxSv32cGIYzdnZzqQwssQ=,tag:6bhQKyfbwVAfJEXce53Zww==,type:str]
#ENC[AES256_GCM,data:9Wwmdo6vib5aji7zwZ4x0A==,iv:QFSfXWjDVX3ERpCv++99xphzTUpinwvtfZAC7JNDvnA=,tag:wK2fm1E8WJv1AEti+eDvGg==,type:comment]
example_array:
- ENC[AES256_GCM,data:D30iuEjIHHkZ+Ho8Vb0=,iv:4IoMVumPllPKl2Z7Uu+nM5ICMKAZtZ3M3rN+R6WCYd0=,tag:QqA7mddoTtBRoX13znRF6w==,type:str]
- ENC[AES256_GCM,data:ShtMmfXXtenrCHLJeak=,iv:HwCESH6ijcdP79rFz7VNvqgOqkZSZ5qeiNLe9O859V4=,tag:6zOVE1/vKVLbDF8Pgj61XA==,type:str]
example_number: ENC[AES256_GCM,data:4xcp+Hv3bUuo,iv:WYrpMJd+fz3BiJdvqrnsQx0MyQ8TcuuW7y0Vedgro30=,tag:16lO59Bmxw6581ysrrpAmw==,type:float]
example_booleans:
- ENC[AES256_GCM,data:scOQAw==,iv:OdIYfIyxoa7939dUZaC4Yuh0sEBnWWGmOxBQRjiCApU=,tag:XshYYGWnu9O1qd1m5/mJbw==,type:bool]
- ENC[AES256_GCM,data:xuWQld4=,iv:GVt35VQDxS13nXbKWIK6NohSEFU/1tCum/psULWwNKw=,tag:jkuGdFtq30fXjDRLXbb+nQ==,type:bool]
appExtConfig:
    SMTP_ADDRESS: ENC[AES256_GCM,data:5D/a4bGLRXGFNJ/U3NmgE29D,iv:ABN8K7bYSiKZsUmGdx9qpmf10EMeScqGgvLqcRMR7rk=,tag:9l/dj8tt0/nCXqzVK8rCig==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:xMnS,iv:7uPaA9MKHGK/RXp5XzM7zK97xknmFb9qy167r6vt7FI=,tag:01m99VQc2VwY3AQGY83/rA==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:BXEdk9zzOpgPAc2srMD2me2aqmSiFifIKFs=,iv:SjeHikxLLsF0jdgQxKhITJwYigZY1AgEYzUx8gQVQFk=,tag:r5N5v2RTMW92UhaDbs82Zg==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:1vBe8fiXUzsh7A==,iv:brTS0bRUJVOmWgHBwGIbt7OgZijmQ+BhCNVapua7TLo=,tag:BDnEP0JwV2GkELqSvyPuxg==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:mV+Dlg==,iv:it5eX8sm9Q/1OfV0q4hpODr2KUrnIHaag7x40vZpEJo=,tag:2kzmixOhgePaNh74542zQw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:hnsQxRgomnAILLMzL+kcy6ZtO1ExfTviz+yshP0DT4cOhDl77U3m6qZsKko=,iv:8o3IFFRezm1MkQeuHQfUNbz4/uZhmJ6r+Ud3Lr73CsU=,tag:MbyqdknMglziM31MK3xzTA==,type:str]
    BASE_URL: ENC[AES256_GCM,data:UenSt1FjiSro1DIIt3g3dweGAUj/MHgToMvFm98NQ1O8TaLsA+TeEyVYu467mZVDVtzEmz7leJHJgYxA7De4qtkio4/j5HGdblXEPGJFkt/cJFG8EQ==,iv:PebzeiYxsEcI0ER91idPQFdy+HZcYNJQva/+vj4ZB2A=,tag:wODDJ507HnyvL+EVeAdogA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2023-10-30T09:07:52Z'
    mac: ENC[AES256_GCM,data:3lZQykq7h0NZKDOYlig6foJpvNkk83oQAiCjK3HEFxrsj/Jn51JMEAwdLUxaqZGYanlB/qUiF2ngsnxGY3OD9jle9F/L9yIYDc+dXRxkHBFLo0gejMYkslLUefdxT/vCj/UWb+qimVBALw+23h6BFzffR5drsE1oe6Ar1q5GX+w=,iv:DOjnrsSUzPSPTv/4uN43lzj0xwIf1LZgMDVm8QiXSds=,tag:T9Rv23HNa9RhywTQd1RSPg==,type:str]
    pgp:
    -   created_at: '2023-10-30T09:00:02Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1gSLZ947okQAQf/UyU3YNuDY1iPch700UUR7jzxU/FFJK3wCYBrW9U+E+pq
            1FS6WV9TZ0CSsrO03nq4TdfxsFqmlSpW2hnlYSS5teQRuDBbwwtPCgxfeQxSWCBG
            7tPDfLmGqkOYezkq7WfE26RVCW++zekZbeDhDN1HSJhCgUR9CqD4UoV0f/yA85Jq
            7aQlQLrmfk2OD2OiO1QXMoPcWaLUwdSD72RWQY0xsf098DP1IKqySYI452NUPsj8
            Q/XR7JvfU1ausKrs4l7HrjVii852vwMhrwSx2kUdtF+xJYzbcQAv1fJaJvcMk3vW
            Y4uXhIDN38LCdzzh58oE2eOVvI0Trp85agB1cZ4TqdJeAYHoGRCIGwXYF2Gvqk96
            i3aiPUVRoPsPtWkSzLRGM6Ittz82gZQWNpWz8YcrTTBxLD2Rj1YxEdNec03Q7xPH
            kQKdGN9Qn/kqeU3pGRVRsURADDjLDMz45SLJR5iscg==
            =fHJn
            -----END PGP MESSAGE-----
        fp: 4C80959A5A0DC7D784CEDE1E1B7F34C12F7B86BE
    unencrypted_suffix: _unencrypted
    version: 3.5.0
